### PR TITLE
Accessibility violations for checkboxes

### PR DESCRIPTION
**Pull request by dmitrykurmanov**
see https://github.com/surveyjs/survey-library/issues/3772

### CODE REVIEW

**Comment by dmitrykurmanov** [comment]
@dszewczyk1 I checked it yesterday and didn't see this message. I'll check it again.

**Comment by dmitrykurmanov** [comment]
> is the `legend` supposed to be empty?

I can't see that errors now:
image

we have only one: "The ARIA attribute 'aria-required, aria-invalid' is not valid for the element "div" with ARIA role 'group'"
but it seems that checker has outdated check. Because in the referenced [doc ](https://www.w3.org/TR/html-aria/#docconformance) we could see the following:

><html>
<body>


div | No corresponding role | Any roleGlobal aria-* attributes and any aria-* attributes applicable to the allowed roles.
-- | -- | --



</body>
</html>

**Comment by dszewczyk1** [comment]
@dmitrykurmanov according to this https://www.w3.org/TR/wai-aria-1.2/#aria-invalid `aria-invalid` and `aria-required` are allowed for specific roles only and probably they're using it for this checker.
`This state is being deprecated as a global state in ARIA 1.2. In future versions it will only be allowed on roles where it is specifically supported.`
Similar violations for aria-invalid and aria-required are shown in the other types, for example: https://surveyjs.io/Examples/Library?id=questiontype-text&platform=Reactjs&theme=modern

**Comment by dmitrykurmanov** [comment]
> @dmitrykurmanov according to this https://www.w3.org/TR/wai-aria-1.2/#aria-invalid `aria-invalid` and `aria-required` are allowed for specific roles only and probably they're using it for this checker. `This state is being deprecated as a global state in ARIA 1.2. In future versions it will only be allowed on roles where it is specifically supported.` Similar violations for aria-invalid and aria-required are shown in the other types, for example: https://surveyjs.io/Examples/Library?id=questiontype-text&platform=Reactjs&theme=modern

Probably we should choose another role for our "checkbox group". Or find some "checkboxes group" example... Here the separate issue: https://github.com/surveyjs/survey-library/issues/3874

**Review by tsv2013 — APPROVED** [review]

**Pull request merged**
