### PR TITLE
fix(#6525):Add string normalization to hasText method

### PR DESCRIPTION
**Pull request by PerikiyoXD**
This is a fix for #6525

### CODE REVIEW

**Review by tsv2013 — COMMENTED** [review]
A test (unit or functional) is nesessary. Otherwise functionality can be lost during future work.

**Comment by PerikiyoXD** [comment]
I'm not familiar with QUnit, I'll investigate and try do some unit testing

**Comment by PerikiyoXD** [comment]
I need help, I'd need to know where to place the test file once I got it ready.

**Comment by andrewtelnov** [comment]
@PerikiyoXD Ι can add a unit test, However, I would make it optional, If you don't mind.
I would add a new option [here](https://github.com/surveyjs/survey-library/blob/master/src/settings.ts#L450) and make it `false` by default.

Thank you,
Andrew

**Comment by PerikiyoXD** [comment]
I'll have a look at it today.

If you can add the test, please do.
 
The configuration will be named `diacriticSensitive`, and will be `false` by default.

I guess this is enough for the test to be made.

**Comment by PerikiyoXD** [comment]
I'm okay with tests being labeled as "optional," but it's essential to include these optional tests in the CI/CD process as well.
Otherwise, if a change accidentally removes this optional status (which ideally should not happen), it won't be caught.
I'm not familiar with the specific setup of the CI/CD pipeline or whether you schedule all test runs, but I just wanted to bring this to your attention.

**Comment by tsv2013** [comment]
Closing in favor of @andrewtelnov PR

**Pull request closed without merging**
