### PR TITLE
Add support for ShadowDOM in SurveyJS Popup Model

### PR DESCRIPTION
**Pull request by skorupaw**
Work for #5703

### CODE REVIEW

**Comment by skorupaw** [comment]
@dmitrykurmanov @andrewtelnov 
As you can see I'm getting some random visual regression test failures, can you guide me please how should I proceed in this situation? 🙂

**Comment by andrewtelnov** [comment]
> @dmitrykurmanov @andrewtelnov As you can see I'm getting some random visual regression test failures, can you guide me please how should I proceed in this situation? 🙂
@skorupaw Sometimes Azure did not start a pipline. We could not figure out the solution. I re-run the failed job.

We will discuss your PR next week and comeback to you.
Thank you for your contribution!
Andrew

**Comment by skorupaw** [comment]
> > @dmitrykurmanov @andrewtelnov As you can see I'm getting some random visual regression test failures, can you guide me please how should I proceed in this situation? 🙂
> 
> @skorupaw Sometimes Azure does not start a pipline. We could not figure out the solution. I re-run the failed job.
> 
> We will discuss your PR next week and comeback to you. Thank you for your contribution! Andrew

Hi @andrewtelnov, thanks for the reply, and for letting me know 🙂 I just want to mention that this PR it's just a part of the full implementation for the https://github.com/surveyjs/survey-library/issues/5703 and I'll happy to finish the remaining parts, you guys give me a green light 😊

**Comment by skorupaw** [comment]
For better visibility, and tracking purposes I created general PR https://github.com/surveyjs/survey-library/pull/5715

**Pull request closed without merging**
